spring:
  application:
    name: products

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/products
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: logs/products.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
